-- SQL syntax for inserts

-- 1 tabel
INSERT INTO formula_1 (reglementari) values ('Sasiu');
INSERT INTO formula_1 (reglementari) values ('Motor');
INSERT INTO formula_1 (reglementari) values ('Anvelope');
INSERT INTO formula_1 (reglementari) values ('Realimentare cu combustibil');
INSERT INTO formula_1 (reglementari) values ('Parc inchis');
INSERT INTO formula_1 (reglementari) values ('Procedura de cursa');
INSERT INTO formula_1 (reglementari) values ('Punctaj');
INSERT INTO formula_1 (reglementari) values ('Penalizare de timp de 5 sau 10 secunde');
INSERT INTO formula_1 (reglementari) values ('Penalizare de tip drive-through');
INSERT INTO formula_1 (reglementari) values ('Penalizari de tip stop-go');
INSERT INTO formula_1 (reglementari) values ('penalizare pe grila');
INSERT INTO formula_1 (pneuri) values ('Pneu SUPERHARD');
INSERT INTO formula_1 (pneuri) values ('Pneu HARD');
INSERT INTO formula_1 (pneuri) values ('Pneu MEDIUM');
INSERT INTO formula_1 (pneuri) values ('Pneu SOFT');
INSERT INTO formula_1 (pneuri) values ('Pneu SUPERSOFT');
INSERT INTO formula_1 (pneuri) values ('Pneu HYPERSOFT');
INSERT INTO formula_1 (pneuri) values ('Pneu INTERMEDIATE');
INSERT INTO formula_1 (pneuri) values ('Pneu WET');
INSERT INTO formula_1 (punctaj) values ('Locul 1 - 25 puncte');
INSERT INTO formula_1 (punctaj) values ('Locul 2 - 18 puncte');
INSERT INTO formula_1 (punctaj) values ('Locul 3 - 15 puncte');
INSERT INTO formula_1 (punctaj) values ('Locul 4 - 12 puncte');
INSERT INTO formula_1 (punctaj) values ('Locul 5 - 10 puncte');
INSERT INTO formula_1 (punctaj) values ('Locul 6 - 8 puncte');
INSERT INTO formula_1 (punctaj) values ('Locul 7 - 6 puncte');
INSERT INTO formula_1 (punctaj) values ('Locul 8 - 4 puncte');
INSERT INTO formula_1 (punctaj) values ('Locul 9 - 2 puncte');
INSERT INTO formula_1 (punctaj) values ('Locul 10 - 1 punct');
INSERT INTO formula_1 (punctaj) values ('Locul 11 - 0 puncte');
INSERT INTO formula_1 (punctaj) values ('Locul 12 - 0 puncte');
INSERT INTO formula_1 (punctaj) values ('Locul 13 - 0 puncte');
INSERT INTO formula_1 (punctaj) values ('Locul 14 - 0 puncte');
INSERT INTO formula_1 (punctaj) values ('Locul 15 - 0 puncte');
INSERT INTO formula_1 (punctaj) values ('Locul 16 - 0 puncte');
INSERT INTO formula_1 (punctaj) values ('Locul 17 - 0 puncte');
INSERT INTO formula_1 (punctaj) values ('Locul 18 - 0 puncte');
INSERT INTO formula_1 (punctaj) values ('Locul 19 - 0 puncte');
INSERT INTO formula_1 (punctaj) values ('Locul 20 - 0 puncte');
INSERT INTO formula_1 (punctaj) values ('Cel mai rapid tur - 1 punct');
INSERT INTO formula_1 (steaguri) values ('Steag VERDE');
INSERT INTO formula_1 (steaguri) values ('Steag GALBEN');
INSERT INTO formula_1 (steaguri) values ('Steag ROSU');
INSERT INTO formula_1 (steaguri) values ('Steag ALBASTRU');
INSERT INTO formula_1 (steaguri) values ('Steag VERDE ALB-NEGRU divizat pe diagonala');
INSERT INTO formula_1 (steaguri) values ('Steag NEGRU');
INSERT INTO formula_1 (steaguri) values ('Steag ALB');
INSERT INTO formula_1 (steaguri) values ('Steag NEGRU cu cerc PORTOCALIU');
INSERT INTO formula_1 (steaguri) values ('Steag cu dungi verticale GALBENE si ROSII');
INSERT INTO formula_1 (steaguri) values ('Steag ALB-NEGRU in carouri');

--2 tabel
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (1, 'Alfa Romeo', 'Elvetia', 1950, True);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (2, 'AlphaTauri', 'Italia', 2020, True);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (3, 'Alpine', 'Franta', 2021, True);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (4, 'Aston Martin', 'Regatul Unit', 1959, True);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (5, 'Ferrari', 'Italia', 1950, True);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (6, 'Haas', 'SUA', 2016, True);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (7, 'McLaren', 'Regatul Unit', 1966, True);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (8, 'Mercedes', 'Germania', 1954, True);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (9, 'RedBull', 'Austria', 2005, True);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (10, 'Williams', 'Regatul Unit', 1978, True);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (11, 'Alfa Special', 'Africa de Sud', 1963, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (12, 'Apollon', 'Elvetia', 1977, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (13, 'Benetton', 'Regatul Unit, Italia', 1986, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (14, 'Boro', 'Tarile de Jos', 1976, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (15, 'Bugatti', 'Franta', 1956, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (16, 'Coloni', 'Italia', 1987, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (17, 'Cooper Car Company', 'Regatul Unit', 1950, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (18, 'Cisitalia', 'Italia', 1952, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (19, 'Eagle', 'SUA', 1966, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (20, 'Force India', 'India', 2008, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (21, 'Honda', 'Japonia', 1964, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (22, 'Jaguar', 'Regatul Unit', 2000, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (23, 'Jordan', 'Irlanda', 1991, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (24, 'Klenk', 'Germania', 1954, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (25, 'Lambo', 'Italia', 1991, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (26, 'Lotus', 'Regatul Unit', 1958, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (27, 'McGuire', 'Australia', 1977, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (28, 'Milano', 'Italia', 1950, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (29, 'Midland', 'Rusia', 2006, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (30, 'Porsche', 'Germania', 1957, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (31, 'Racing Point', 'Regatul Unit', 2018, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (32, 'Renault', 'Franta, Regatul Unit', 1977, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (33, 'Rial', 'Elvetia', 1988, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (34, 'Sauber', 'Elvetia', 1993, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (35, 'Stebro', 'Canada', 1963, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (36, 'Toyota', 'Japonia', 2002, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (37, 'Toro Rosso', 'Italia', 2006, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (38, 'Wolf', 'Canada', 1977, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (39, 'Virgin', 'Regatul Unit, Rusia', 2010, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (40, 'Theodore', 'Hong Kong', 1978, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (41, 'Super Aguri', 'Japonia', 2006, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (42, 'Prost', 'Franta', 1997, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (43, 'Pacific', 'Regatul Unit', 1994, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (44, 'Martini', 'Franta', 1978, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (45, 'LDS', 'Africa de Sud', 1962, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (46, 'Greifzu', 'Germania de Est', 1953, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (47, 'Fry', 'Regatul Unit', 1959, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (48, 'Fittipaldi Automotive', 'Brazilia', 1975, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (49, 'EuroBurn', 'Italia', 1988, False);
INSERT INTO echipe (formula_1_id, nume, tara_origine, an_infiintare, existente) values (50, 'Caterham', 'Malaezia', 2012, False);

--3 tabel
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Bruno Famin', 1, 'bruno.famin@f1.com', 'Alpine');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Frederic Vasseur', 1, 'fred.vas@f1.com', 'Ferrari');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Andreas Seidl', 1, 'and.sei@f1.com', 'Alfa Romeo');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Christian Horner', 18, 'chr.hor@f1.com', 'RedBull');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Mike Krack', 3, 'mik.kra@f1.com', 'Aston Martin');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Gunther Steiner', 8, 'gun.ste@f1.com', 'Haas');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Franz Tost', 17, 'fra.tos@f1.com', 'AlphaTauri');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Toto Wolff', 11, 'tot.wol@f1.com', 'Mercedes');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('James Vowles', 1, 'jam.vow@f1.com', 'Williams');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Andrea Stella', 1, 'and.ste@f1.com', 'McLaren');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('George Abecassis', 3, 'geo.abe@f1.com', 'HWM');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Ove Andersson', 1, 'ove.and@f1.com', 'Toyota');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Maurizio Arrivabene', 7, 'mau.ari@f1.com', 'Ferrari');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('John Booth', 5, 'joh.boo@f1.com', 'Virgin');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Eric Boullier', 8, 'eri.bou@f1.com', 'Renault');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Ross Brawn', 6, 'ros.bra@f1.com', 'Honda');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Jack Brabham',121, 'jac.bra@f1.com', 'Brabham');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Eric Broadley', 1, 'eri.bro@f1.com', 'Lola');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Flavio Briatore', 16, 'fla.bri@f1.com', 'Benetton');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Jost Capito', 2, 'jos.cap@f1.com', 'Williams');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Trevor Carlin', 1, 'tre.car@f1.com', 'Midland');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Colin Chapman', 23, 'col.cha@f1.com', 'Lotus');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Walter Burn', 3, 'val.bur@f1.com', 'EuroBurn');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Enzo Coloni', 7, 'enz.col@f1.com', 'Coloni');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Vijay Mallya', 10, 'vij.mal@f1.com', 'Force India');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Eddie Jordan', 12, 'edd.jor@f1.com', 'Jordan');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Ernesto Vita', 1, 'ern.vit@f1.com', 'Life');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Giancarlo Minardi', 25, 'gia.mic@f1.com', 'Minardi');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Fritz Huschke von Hanstein', 8, 'fri.hus@f1.com', 'Porsche');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Alain Prost', 5, 'ala.pro@f1.com', 'Prost');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Otmar Szafnauer', 3, 'otm.sza@f1.com', 'Racing Point');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Gunter Schmid', 2, 'gun.smd@f1.com', 'Rial');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Peter Sauber', 10, 'pet.sau@f1.com', 'Sauber');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Alexander von Falkenhausen', 3, 'ale.fal@f1.com', 'AFM');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Andrea Sassetti', 1, 'and.sas@f1.com', 'Andrea Moda');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Rocco Benetton', 13, 'roc.ben@f1.com', 'Benetton');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Mario Theissen', 4, 'mar.the@f1.com', 'BMW Sauber');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Ross Brawn', 1, 'ros.bra@f1.com', 'Brawn');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Cyril Abiteboul', 3, 'cyr.abi@f1.com', 'Caterham');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Guido Forti', 2, 'gui.for@f1.com', 'Forrti Corse');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Gerard Lopez', 3, 'ger.lop@f1.com', 'Lotus');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Stephen Fitzpatrick', 1, 'ste.fit@f1.com', 'Manor');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Ron Dennis', 18, 'ron.den@f1.com', 'McLaren');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Jackie Stewart', 4, 'jac.ste@f1.com', 'Stewart');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Erich Zakowski', 4, 'eri.zak@f1.com', 'Zakspeed');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Ken Tyrrell', 23, 'ken.tyr@f1.com', 'Tyrrell');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Mattia Binotto', 5, 'mat.ben@f1.com', 'Ferrari');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Alfred Neubauer', 2, 'alf.neu@f1.com', 'Mercedes');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Paul Stoddart', 4, 'pau.sto@f1.com', 'Minardi');
INSERT INTO manageri (nume, ani_vechime, email, echipa) values ('Frederic Vasseur', 1, 'fre.vas@f1.com', 'Renault');

--4 tabel
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Max Verstappen', 23, 'RedBull', 3);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Sergio Perez', 36, 'RedBull', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Charles Leclerc', 22, 'Ferrari', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Crlos Sainz', 26, 'Ferrari', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Lando Norris', 22, 'McLaren', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Oscar Piastri', 21, 'McLaren', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Lewis Hamilton', 38, 'Mercedes', 7);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('George Russel', 24, 'Mercedes', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Valtteri Bottas', 34, 'Alfa Romeo', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Zhou Guanyu', 29, 'Alfa Romeo', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Pierre Gasly', 26, 'Alpine', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Esteban Ocon', 29, 'Alpine', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Fernando Alonso', 42, 'Aston Martin', 2);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Lance Stroll', 27, 'Aston Martin', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Kevin Magnussen', 37, 'Haas', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Nico Hulkenberg', 38, 'Haas', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Yuki Tsunoda', 24, 'AlphaTauri', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Daniel Ricciardo', 26, 'AlphaTauri', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Alexander Albon', 27, 'Williams', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Logan Sargeant', 24, 'Williams', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Michael Schumacher', 47, 'Ferrari', 7);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Mick Schumacher', 23, 'Haas', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Alain Prost', 57, 'McLaren', 4);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Sebastian Vettel', 46, 'Aston Martin', 4);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Niki Lauda', 70, 'Brabham', 3);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Ayrton Senna', 34, 'Lotus', 3);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Mika Hakkinen', 55, 'McLaren', 2);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Kimi Raikkonen', 51, 'Alfa Romeo', 1);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Nico Rosberg', 38, 'Mercedes', 1);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Nelson Piquet', 41, 'Benetton', 3);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Alan Jones', 77, 'Lola', 1);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Keke Rosberg', 75, 'ATS', 1);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Damon Hill', 62, 'Jordan', 1);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Nigel Ernest', 70, 'Lotus', 1);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Jackie Stewart', 84, 'Tyrrell', 3);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Liam Lawson', 22, 'AlphaTauri', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Nicholas Latifi', 27, 'Williams', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Nikita Mazepin', 24, 'Haas', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Antonio Giovinazzi', 29, 'Alfa Romeo', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Romain Grosjean', 36, 'Haas', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Robert Doornbos', 42, 'RedBull', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Esteban Gutierrez', 32, 'Sauber', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Nyck de Vries', 23, 'AlphaTauri', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Alexander Rossi', 32, 'Marussia', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Jack Aitken', 28, 'Williams', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Bruno Senna', 40, 'Renault', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Scott Speed', 40, 'Toro Rosso', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Mark Webber', 47, 'Porsche', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('David Brabham', 58, 'Brabham,', 0);
INSERT INTO piloti (nume, varsta, echipa, campionate_castigate) values ('Sebastian Buemi', 35, 'Toro Rosso', 0);

-- 5 tabel
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('C43', 'Alfa Romeo', 'rosu, alb, verde');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('C42', 'Alfa Romeo', 'rosu, alb, verde');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('C41', 'Alfa Romeo', 'rosu, alb, verde');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('AT04 RBPT', 'AlphaTauri', 'albastru, alb');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('AT03 RBPT', 'AlphaTauri', 'albastru, alb');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('AT02 RBPT', 'AlphaTauri', 'albastru, alb');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('A523', 'Alpine', 'albastru, roz');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('A522', 'Alpine', 'albastru, roz');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('A521', 'Alpine', 'albastru, roz');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('AMR23', 'Aston Martin', 'verde, galben, negru');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('AMR22', 'Aston Martin', 'verde, galben, negru');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('AMR21', 'Aston Martin', 'verde, galben, negru');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('SF-23', 'Ferrari', 'rosu, alb, negru');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('SF-22', 'Ferrari', 'rosu, alb, negru');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('SF-21', 'Ferrari', 'rosu, alb, negru');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('VF-23', 'Haas', 'rosu, alb, negru');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('VF-22', 'Haas', 'rosu, alb, negru');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('VF-21', 'Haas', 'rosu, alb, negru');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('MCL60', 'McLaren', 'portocaliu, negru, albastru, alb');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('MCL36', 'McLaren', 'portocaliu, negru, albastru, alb');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('MCL35', 'McLaren', 'portocaliu, negru, albastru, alb');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('F1 W14 E', 'Mercedes', 'negru, turqoise, alb');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('F1 W13 E', 'Mercedes', 'negru, turqoise, alb');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('F1 W12 E', 'Mercedes', 'negru, turqoise, alb');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('RB19', 'RedBull', 'rosu, albastru, galben, alb');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('RB18', 'RedBull', 'rosu, albastru, galben, alb');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('RB16', 'RedBull', 'rosu, albastru, galben, alb');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('FW45', 'Williams', 'albastru, negru, portocaliu');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('FW44', 'Williams', 'albastru, negru, portocaliu');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('FW43B', 'Williams', 'albastru, negru, portocaliu');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('72D', 'Lotus', 'negru, auriu, rosu');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('T370', 'Lola', 'rosu, alb, negru');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('191', 'Jordan', 'verde, albastru, rosu');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('BT45', 'Brabham', 'rosu, albatru, alb, negru');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('C33', 'Sauber', 'negru, alb, rosu');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('STR12', 'Toro Rosso', 'albastru, rosu, alb');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('R.S.17', 'Renault', 'negru, galben, alb');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('RSK', 'Porsche', 'gri, alb, negru');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('RA272', 'Honda', 'alb, negru, rosu');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('P57', 'BRM', 'negru, alb');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('009', 'Tyrrell', 'albastru, rosu, verde, alb');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('FW45', 'Williams', 'albastru, negru, portocaliu');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('WR7', 'Wolf', 'negru, alb, rosu');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('841', 'Zakspeed', 'rosu, alb, negru, galben');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('ER-188', 'EuroBurn', 'alb, galben, negru');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('B188', 'Benetton', 'albastru, verde, galben, rosu, negru');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('C4', 'Coloni', 'albastru, alb');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('291', 'Lambo', 'albastru, alb, galben, rosu');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('M191', 'Minardi', 'negru, galben, alb');
INSERT INTO masini (denumire, echipa_apartinatoare, culori) values ('AP01', 'Prost', 'albastru, alb');

--6 tabel
INSERT INTO circuite (nume, tara, nr_accidente, nr_tururi) values ()